---
- name: Deploy Docker Compose Application
  hosts: docker
  become: true

  tasks:

    - name: Copy application files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /opt/cicd-web/
        owner: ubuntu
        group: ubuntu

    - name: Build and start application with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/cicd-web
        build: always
        state: present
